requires 'Mojolicious',                  '>= 9.31';
requires 'Mojolicious::Plugin::OpenAPI', '>= 5.09';

on 'test' => sub {
    requires 'Perl::Critic', '>= 1.150';
    requires 'Perl::Tidy',   '>= 20221112';
    requires 'Path::Tiny',   '>= 0.144';
};