name: Continuous Integration Workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

env:
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG:  ${{ github.sha }}
  REGISTRY:   ghcr.io

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=gha
          cache-to:   type=gha,mode=max
          outputs:    type=docker, dest=/tmp/container.tar
          labels: ${{ steps.meta.outputs.labels }}
          tags:   ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Upload container artifact
        uses: actions/upload-artifact@v3
        with:
          name: container.tar
          path: /tmp/container.tar


  tidy:
    name: Run perl tidy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Download container artifact
        uses: actions/download-artifact@v3
        with:
          name: container.tar
          path: /tmp

      - name: Run perl tidy
        run: |
          docker load --input /tmp/container.tar
          docker run ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} tidy --check-only

  critic:
    name: Run perl critic
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Download container artifact
        uses: actions/download-artifact@v3
        with:
          name: container.tar
          path: /tmp

      - name: Run perl critic
        run: |
          docker load --input /tmp/container.tar
          docker run ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} critic