name: Continuous Integration Workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

env:
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG:  ${{ github.sha }}
  REGISTRY:   ghcr.io

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=gha
          cache-to:   type=gha,mode=max
          labels: ${{ steps.meta.outputs.labels }}
          tags:   ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
